export enum EventType {
    bolus = 'Bolus',
    smb = 'SMB',
    isExternal = 'External Insulin',
    mealBolus = 'Meal Bolus',
    correctionBolus = 'Correction Bolus',
    snackBolus = 'Snack Bolus',
    bolusWizard = 'BolusWizard',
    tempBasal = 'TempBasal',
    tempBasalDuration = 'TempBasalDuration',
    pumpSuspend = 'PumpSuspend',
    pumpResume = 'PumpResume',
    pumpAlarm = 'PumpAlarm',
    pumpBattery = 'PumpBattery',
    rewind = 'Rewind',
    prime = 'Prime',
    journalCarbs = 'JournalEntryMealMarker',
    nsTempBasal = 'Temp Basal',
    nsCarbCorrection = 'Carb Correction',
    nsTempTarget = 'Temporary Target',
    nsInsulinChange = 'Insulin Change',
    nsSiteChange = 'Site Change',
    nsBatteryChange = 'Pump Battery Change',
    nsAnnouncement = 'Announcement',
    nsSensorChange = 'Sensor Start',
    capillaryGlucose = 'BG Check',
    nsExercise = 'Exercise',
}
